package es.rdboboia.custom.starter.api.dto.product;

import es.rdboboia.custom.starter.api.dto.producttype.ProductTypeDto;
import es.rdboboia.custom.starter.persistence.entity.Product;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/** {@link Product} DTO. */
@Schema(
    description =
        "Product object that will be sent to the server to create a new product. "
            + "It does not contain the id, as it will be generated by the server.")
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
public class ProductWithoutIdDto {

  @NotBlank
  @Schema(description = "Product name", example = "Some product name")
  private String name;

  @NotNull
  @Valid
  @Schema(description = "Product type")
  private ProductTypeDto type;
}
